backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:

  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Publicaciones" # Used in the UI
    label_singular: "Publicación"
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter

      - label: "Título"
        name: "title"
        widget: "string"

      - label: "Incluir en menu"
        name: "menu"
        required: false
        widget: "select"
        options: [{label: "Principal", value: "main"}]

      - label: "Fecha de Publicacíión"
        name: "date"
        required: false
        widget: "datetime"

      - label: "Categorías"
        name: "categories"
        required: false
        widget: "list"

      - label: "Etiquetas"
        name: "tags"
        required: false
        widget: "list"

      - label: "Palabras clave"
        name: "keywords"
        required: false
        widget: "list"

      - label: "Autor"
        name: "author"
        required: false
        widget: "string"

      - label: "Imágen del autor"
        name: "authorAvatar"
        required: false
        widget: "image"

      - label: "Imágen"
        name: "image"
        required: false
        widget: "image"

      - label: "Contenido"
        name: "body"
        widget: "markdown"
